import = [
    "~/.config/alacritty/themes/themes/seashells.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

dynamic_title = true
decorations = "Transparent"
opacity = 0.85

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape="Beam"
style.blinking="Always"

[keyboard]
bindings = [
  { key = "S", mods = "Control|Shift|Option|Command", action="Hide"},
]
